# Generated by Django 6.0.3 on 2026-03-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='shop/image')),
            ],
        ),
    ]
